"use client";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { useRef } from "react";

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const cursor = useRef(null);
  const changePosition = (e) => {
    cursor.current.style.top = `${e.clientY}px`;
    cursor.current.style.left = `${e.clientX}px`;
  };
  return (
    <html lang="en">
      <body className={montserrat.className} onMouseMove={changePosition}>
        {children}
        <div className="cursor-style" id="cursor" ref={cursor}></div>
      </body>
    </html>
  );
}
